language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: i9wT6VLjfkIUiVOY9+SA8koeCIHdyIoXXiqqaev9LJwEHCCU2d1j3FJpDXtqCdmJcjWViUd+UR5pRuwmzRDzYq7fLoxSnNroewikCYrf9tfKL945roHLdOxd2n1/VMaYd8ONH9OzuJK9HMGaScTB0LhATIYqYvV6xV8ZEaC9QcQ8GJx+ZH7Iz3/utNXmO+GyoNGpEB/YZAmFdbAY+MlDxSjqf1unlVhcVm4TTnsEV8zdtwJNt7l74ecA3HezyQI6wtC/GLhMm0DPKNf6j6Amsr32H80VB9TUfhnU2IucdDKlpDOFd1/ri9D/Qsy5sna4/9wZujx7QGV1gk+67Nv6YV7QltF8RhoRZVPB1DgsgB7j4EsG570dRSV9z0jsPWda1TIuG1DlQxRqKi1cJemd+4hLoBhaUURfbzVQxV9kAl9g82/xI2cAUKqarlcPRGJCJcdNIzRWyCI4gGvNT3sQb+qn71SJm9eDZDeStzbBRjz8jqIoaFdQvYGZSkM2qOz33P9R6gEBx44R4ZgBixJ/zAu4MW2VNCxbEbv6Q+BY7ZPQD/QfejKi4vcUudDd/a93LDsHZHAxIv2UWj7mq0yjYDJYRZfRRsg5RQfnFXNCiLHgJcJuP9Tv5qhMLiNJKdgYjrafg7yP1CF75vpvcjfCja07Rdyuf7iDoFOwKlk55Rk=
  app: ccrancidtomatillos
  skip_cleanup: true
  on: 
    branch: main