language: node_js
node_js:
- node
notifications:
  email: false
# deploy:
#   api_key:
#     secure: JcuGs4HuhYDwOqREyS5fEhJtOIWB0IGltNy2M6/u4GUBoj2O0XvHpoiohCdPw3SxW0zARM5YUw+ZOj5czxOrPe8vhUZ/SP/0iLtzY9Q1rbQPhphCMQA+0B6ZVyNCL9+evfrf2MHGD9Kd5G5mSoTJ9fBibTxSkMAMiTMNCaLjgfF2ZSLEtokhWfL57pTMfsepIfRcpjyNpDjYYXFS9+ZpA+d5E8TsAMuXGYdUYvZbkzHoMuot1vwh3ezssQifE9QaX01gUPjLB2b1Ka9Cob2SN4wAdIXNQhN2KzmRvHU0Rid3Sy+fPMKfGuoyLXy1gX2PKbgVvRPYxMMy2OOPcNSIJ5saay+rS/nwS6Akbpd0nq4um0lmsIbDs5IEERFE/a3podGe4Fa9ho6sZtMKjchbDDu74x31kZhTpuwnWFEhEyyQQjmNUDZH+GYOmKcpBdk9njwkQJJxHQ5tn3FJGUCrUFkZZGXdPQ4BIWptfsuOq2CXnA/dxtzDAiGmSGb/vfYuhW2nKjhIFbwWPkpWlAJcMGZ5KDiBVKIuOWGUvxZGG7lcQ+lmCfvR6ebbbXtnbHMNSR81X4K0QJ5/GXp3HMnut68jS9NRrCKCFArq3495LxB8cBjEn/2NDI7/kkMU860450qieUrpHr0gNmzwqU/F9+G2tm1zdy80pYAFKrlu5aM=
